package com.dangxuanthong.firebase.firestore.utils

import com.dangxuanthong.firebase.firestore.exceptions.asFirestoreException
import fdb.FdbCallback
import kotlin.coroutines.resumeWithException
import kotlinx.cinterop.COpaquePointer
import kotlinx.cinterop.StableRef
import kotlinx.cinterop.readBytes
import kotlinx.cinterop.staticCFunction
import kotlinx.coroutines.CancellableContinuation
import kotlinx.coroutines.suspendCancellableCoroutine

/**
 * Executes an asynchronous native C function generated by cinterop within a coroutine scope.
 *
 * This function bridges C-style asynchronous callbacks ([FdbCallback]) into idiomatic Kotlin
 * coroutine suspension. It manages the lifecycle of the [StableRef] pointer passed as `userdata`
 * and handles success, failure, and immediate native error return codes.
 *
 * ### Mandatory Usage Rules:
 * 1. **Pass `userdata` and `callback` to the Native C Function:**
 *    At the usage site, the [nativeFunction] lambda receives `userdata` ([COpaquePointer]) and `callback` ([FdbCallback]).
 *    You **must** pass both `userdata` and `callback` directly into the C interop function parameter list.
 *
 * 2. **Call [NativeCallConfig.onSuccess] inside [config]:**
 *    Inside the [config] builder block, you **must** invoke [NativeCallConfig.onSuccess] to specify how the raw
 *    payload `ByteArray?` is mapped into the return type [T]. Omission will cause a runtime [IllegalArgumentException].
 *
 * ### Example Usage:
 * ```kotlin
 * val snapshot: DocumentSnapshot = suspendNativeCall(
 *     nativeFunction = { userdata, callback ->
 *         fdb_fs_get(doc_path = path, userdata, callback)
 *     },
 *     config = {
 *         onSuccess { bytes -> DocumentSnapshot(bytes) }
 *     }
 * )
 * ```
 *
 * @param T The return type of the suspended operation.
 * @param nativeFunction A lambda providing `userdata` ([COpaquePointer]) and `callback` ([FdbCallback]) to be forwarded
 * to the native C function. The C function must return a `Long` status or return code (`rc`).
 * @param config Builder block for [NativeCallConfig]. Must invoke [NativeCallConfig.onSuccess].
 *
 * @return The parsed object of type [T] when the native callback completes successfully (`seq > 0`).
 *
 * @throws IllegalArgumentException If [NativeCallConfig.onSuccess] is not invoked within the [config] block.
 * @throws Throwable Exception mapped by [NativeCallConfig.onError] if the native function returns an immediate error code (`rc < 0`),
 * or mapped by [NativeCallConfig.onFailure] if the native callback returns a failure sequence code (`seq <= 0`).
 */
suspend fun <T : Any> suspendNativeCall(
    nativeFunction: (userdata: COpaquePointer, callback: FdbCallback) -> Long,
    config: NativeCallConfig<T>.() -> Unit
): T = suspendCancellableCoroutine { cont ->
    val nativeCallConfig = NativeCallConfig(cont).apply(config)
    require(nativeCallConfig.check()) { "onSuccess must be called inside NativeCallScope block" }

    val ref = StableRef.create(nativeCallConfig)
    val rc = nativeFunction(
        ref.asCPointer(),
        staticCFunction { userdata, seq, payload, len ->
            userdata!!.useAsStableRef<NativeCallConfig<T>> { (cont, onSuccess, onFailure) ->
                val bytes = payload?.readBytes(len.toInt())?.takeIf { it.isNotEmpty() }
                cont.resumeWith(
                    runCatching {
                        if (seq > 0) onSuccess(bytes)
                        else throw onFailure(bytes, seq)
                    }
                )
            }
        }
    )
    if (rc < 0L) {
        ref.dispose()
        cont.resumeWithException(nativeCallConfig.error(rc))
    }
}

/**
 * Configuration builder scope for [suspendNativeCall].
 *
 * Holds callbacks for mapping success payloads, failure sequences, and native return code errors.
 *
 * @param T The expected return type of the suspend operation.
 */
class NativeCallConfig<T> internal constructor(
    internal val continuation: CancellableContinuation<T>
) {
    internal lateinit var success: (ByteArray?) -> T
        private set
    internal var failure: (ByteArray?, Long) -> Throwable = { bytes, _ ->
        bytes.asFirestoreException()
    }
        private set
    internal var error: (Long) -> Throwable = {
        when (it) {
            -1L -> IllegalStateException("You must call Firebase.initialize first.")
            else -> RuntimeException("Operation failed with unknown code: $it.")
        }
    }
        private set

    /**
     * Registers the success transformation lambda.
     *
     * **MANDATORY:** This function **must** be called inside the `config` block of [suspendNativeCall].
     *
     * @param block A lambda that transforms the raw `ByteArray?` payload into the result object [T].
     */
    fun onSuccess(block: (bytes: ByteArray?) -> T) {
        success = block
    }

    /**
     * Registers a custom failure handler for asynchronous native errors (`seq <= 0`).
     *
     * If not called, defaults to decoding the Firestore exception payload using [ByteArray.asFirestoreException].
     *
     * @param block A lambda mapping raw payload bytes and sequence code `Long` to a [Throwable].
     */
    fun onFailure(block: (bytes: ByteArray?, seq: Long) -> Throwable) {
        failure = block
    }

    /**
     * Registers a custom error handler for immediate native return code errors (`rc < 0`).
     *
     * @param block A lambda mapping the return code `Long` to a [Throwable].
     */
    fun onError(block: (rc: Long) -> Throwable) {
        error = block
    }

    internal fun check() = ::success.isInitialized

    internal operator fun component1() = continuation
    internal operator fun component2() = success
    internal operator fun component3() = failure
}
